
version: '3.3'
services:
  n8nio:
    container_name: n8n
    restart: always
    ports:
      - '5678:5678'
    volumes:
      - '/data/docker/n8n:/home/node/.n8n'
    image: n8nio/n8n:latest
    environment:
      - 'WEBHOOK_URL=https://mini-n8n.110.com/'